(* This file is autogenerated.  Do not modify *)
open OUnit

let suite = "Test Suite" >::: [
  "FuzzySetTest.test_create" >:: FuzzySetTest.test_create;
  "FuzzySetTest.test_create_triangle" >:: FuzzySetTest.test_create_triangle;
  "FuzzySetTest.test_to_s" >:: FuzzySetTest.test_to_s;
  "FuzzySetTest.test_mu" >:: FuzzySetTest.test_mu;
  "FuzzySetTest.test_product" >:: FuzzySetTest.test_product;
  "FuzzySetTest.test_combine_max" >:: FuzzySetTest.test_combine_max;
  "FuzzySetTest.test_x_cdg" >:: FuzzySetTest.test_x_cdg;
];;

run_test_tt_main suite